version: '3'

services:
  map:
    image: mhajder/openstreetmap-tile-server-cyclosm
    volumes:
      - openstreetmap-data:/var/lib/postgresql/12/main
    ports:
      - "8080:80"
    command: "run"

volumes:
  openstreetmap-data:
    external: true
